language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots  #libsdl2
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install libsdl2-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make