language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install apt-get build-essential
  - sudo apt-get -qq install libglew-dev libsdl1.2-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DTHREE_HEADER_ONLY:BOOL=OFF

script: make